### ISSUE TITLE
问题1

### ISSUE THREAD

**Issue by BoCodeSailor** [LiuZengqiang/HeliostatFieldLayout#1]
请问你是否可以提供关于定日镜场布局的代码？

**Comment by Brilliant-Joe** [comment]
I won't.

**Comment by LiuZengqiang** [comment]
> 

你是想得到“定日镜布局的数据文件”还是“根据指定要求自动生成镜场布局的代码”？如果是前者，那这个仓库，就是所有可以给你的数据了。如果是后者，暂时还没有。或者你可以更详细地描述你的需求。
